# Generated by Django 5.1.3 on 2026-04-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('status', models.CharField(choices=[('in-stock', 'En Stock'), ('low-stock', 'Stock Bajo'), ('out-stock', 'Agotado')], default='in-stock', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Producto / Insumo',
                'verbose_name_plural': 'Productos / Insumos',
                'ordering': ['name'],
            },
        ),
    ]
